### ISSUE TITLE
Run in background

### ISSUE THREAD

**Issue by shlomiuni** [PragmaTwice/proxinject#11]
Hi, I was wondering if it's possible for you to add a command that will run the tool in the background?
I'm trying to use that tool to run some programs but I don't want my users to see the cmd windows :(
Thanks!

**Comment by PragmaTwice** [comment]
Hi @shlomiuni , I think you can easily hide the console window while you are calling some process-creation win32 APIs, e.g.
you can pass `CREATE_NO_WINDOW` to `CreateProcess` to hide it.

```c++
   BOOL creationResult;
    
    creationResult = CreateProcess(
        NULL,                   // No module name (use command line)
        "<the cmd line for proxinjector-cli>",                // Command line
        NULL,                   // Process handle not inheritable
        NULL,                   // Thread handle not inheritable
        FALSE,                  // Set handle inheritance to FALSE
        CREATE_NO_WINDOW, // creation flags
        NULL,                   // Use parent's environment block
        NULL,                   // Use parent's starting directory 
        &startupInfo,           // Pointer to STARTUPINFO structure
        &processInformation);   // Pointer to PROCESS_INFORMATION structure
```

refer to https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags

**Comment by shlomiuni** [comment]
> Hi @shlomiuni , I think you can easily hide the console window while you are calling some process-creation win32 APIs, e.g. you can pass `CREATE_NO_WINDOW` to `CreateProcess` to hide it.
> 
> ```c++
>    BOOL creationResult;
>     
>     creationResult = CreateProcess(
>         NULL,                   // No module name (use command line)
>         "<the cmd line for proxinjector-cli>",                // Command line
>         NULL,                   // Process handle not inheritable
>         NULL,                   // Thread handle not inheritable
>         FALSE,                  // Set handle inheritance to FALSE
>         CREATE_NO_WINDOW, // creation flags
>         NULL,                   // Use parent's environment block
>         NULL,                   // Use parent's starting directory 
>         &startupInfo,           // Pointer to STARTUPINFO structure
>         &processInformation);   // Pointer to PROCESS_INFORMATION structure
> ```
> 
> refer to https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags

Thank you for the answer.
Is that where you call the process creation in your code?
```
injector_cli.cpp
 for (const auto &file : create_paths) {
    DWORD creation_flags = parser.get<bool>("-w") ? CREATE_NEW_CONSOLE : 0;
    if (auto res = create_process(file, creation_flags)) {
      if (server.inject(res->dwProcessId)) {
        report_injected(res->dwProcessId);
      }
    }
  }
```

**Comment by PragmaTwice** [comment]
Nope, I mean you can pass these flags in your own code for creating a proxinjector-cli process without a console window.

I think it is not something that this project will do.

**Comment by PragmaTwice** [comment]
Closed. Feel free to open if you have further questions.
