### ISSUE TITLE
Add process by name support regular expression

### ISSUE THREAD

**Issue by freechar** [PragmaTwice/proxinject#8]
Hello , Please add process support regular expression by process name

**Comment by PragmaTwice** [comment]
Hi, this feature has been added to the master branch, and will be included in the next release (maybe 0.4.3, which will be published soon).

You can wait for the next release to experience it, or retrieve the snapshot binary [from CI](https://github.com/PragmaTwice/proxinject/actions/runs/3651373384) / build the current master by your own.
