### ISSUE TITLE
add process search in directories with regular expressions

### ISSUE THREAD

**Issue by sanch1z** [PragmaTwice/proxinject#9]
Hello, I really like your application and I really miss such functionality as in Proxifire (https://www.proxifier.com/). There you can add a search for proxied applications using regular expressions. Can you implement something like this? Thank you!

Example: C:/programs/\*/\*.exe

https://ibb.co/PY920v7

**Comment by PragmaTwice** [comment]
Thanks for your issue. It seems someone has already requested this feature in #8.

As responsed in #8, it sounds an interesting and easy-to-implement feature. I will implement it while I am free.

**Comment by PragmaTwice** [comment]
Hi, this feature has been added to the master branch, and will be included in the next release (maybe 0.4.3, which will be published soon).

You can wait for the next release to experience it, or retrieve the snapshot binary [from CI](https://github.com/PragmaTwice/proxinject/actions/runs/3651373384) / build the current master by your own.
